IDS_nodokaSetup, _T("のどか セットアップ"),
IDS_nodokaRunning, _T("のどか が動作中です。終了させて作業を続けますか?\n最大60秒待ちます。"),
IDS_nodokaEmpty, _T("インストール先を指定してください。"),
IDS_selectDir, _T("インストール先を指定してください。"),
IDS_invalidDirectory, _T("不正なディレクトリです。"),
IDS_removeOk, _T("のどか をアンインストールしてよろしいですか？"),
IDS_removeFinish, _T("のどか はアンインストールされました。"),
IDS_copyFinish, _T("インストールが終了しました。\n一度ログオフする必要があります。\n今すぐログオフしますか?"),
IDS_error, _T("インストール中にエラーが発生しました。"),
IDS_alreadyUninstalled, _T("のどか のアンインストールが既に実行されています。\n再起動してからインストールしなおしてください。"),
IDS_notAdministrator, _T("Administrator で実行してください。"),
IDS_invalidOS, _T("この OS では動作しません。"),
IDS_nodokaFile, _T("のどか ファイル"),
IDS_nodokaShellOpen, _T("notepad.exe \"%1\""),
IDS_nodoka, _T("のどか"),
IDS_nodokad, _T("のどか ドライバ"),
IDS_shortcutName, _T("のどか"),
IDS_shortcutName2, _T("dotnet_starter"),
IDS_keyboard109usb, _T("日本語 109 (106) キーボード"),
IDS_keyboard104usb, _T("英語 104 (101) キーボード"),
IDS_dotnodoka, _T("dotjp.nodoka"),
IDS_copyFinishUsb, _T("インストールが終了しました。\nコンピュータを再起動する必要があります。\n今すぐ再起動しますか?"),
IDS_failedToReboot, _T("再起動に失敗しました。「のどか」を実行する前に必ず再起動してください。"),
IDS_installerror, _T("インストール中にエラーが発生しました。\n再起動してからインストールしなおしてください。"),
IDS_detectfilterdriver, _T("キーボードクラスのデバイスドライバを検出しました。\nインストールしても、うまく動作しない可能性があります。\nユーザ責任となりますが、インストールを続行させますか。"),
IDS_selectDirNODOKA, _T("環境変数NODOKAに指定するフォルダを指定してください。設定ファイルの参照先に使います。"),
IDS_shortcutNameGUI, _T("のどかGuiEdit"),
IDS_note01, _T("インストール時の注意とライセンスについて\r\n\r\n"),
IDS_note02, _T("　「のどか」は、キーボードクラスのフィルタデバイスドライバを用いたキーリマップツールです。"),
IDS_note03, _T("そのため標準とは異なるキーボードフィルタドライバがインストールされている場合、「のどか」は正常動作できない可能性があるため、インストール途中で注意を促すダイアログを表示します。"),
IDS_note04, _T("ユーザー判断となりますがその場合には、そのフィルタドライバを用いるソフトを、あらかじめアンインストールしてください。\r\n\r\n"),
IDS_note05, _T("　そのようなソフトとは、Logicool社キーボードやマウスに付属のSetPointやメーカー製のPCにプリインストールされているキーボードカスタマイズユーティリティなどです。\r\n\r\n"),
IDS_note06, _T("　「のどか」のバージョンアップインストールの際、デバイスドライバを正常に登録できずに、インストールが終了することがあります。"),
IDS_note07, _T("　その場合には、PCを再起動してから、インストール作業をやり直してください。\r\n\r\n"),
IDS_note08, _T("　ライセンスは、EPL 2.0(Eclipse Public License 2.0)です。詳細は zipファイル内に同梱されているLICENSE.txt（英語）、LICENSE_JP.txt（日本語参考訳）を、ご覧ください。\r\n\r\n"),
IDS_note09, _T("　デバイスドライバやアプリケーションプログラムのデジタル署名のために、シェアウェアとなっています。試用版は、起動後30分で自動的に終了します。それ以外に正式版との差はありません。\r\n\r\n"),
IDS_note10, _T("　ソフトウェアおよびドキュメントの不具合解消に努めていますが、なんらかの誤り、不具合、事故が発生した場合、その責任は、使用者にあります。"),
IDS_note11, _T("御理解頂けない場合には、ただちに御利用を、おやめ下さい。"),
IDS_note12, _T("なお、対応できないダメなケースもあるでしょうが、バグ報告頂いた場合には、誠意を持って可能な限り対応いたします。\r\n\r\n"),
IDS_note13, _T("　新バージョンリリースの際、メジャーバージョンアップ以外では、シェアウェア費用を再度支払う必要はありません。"),
IDS_note14, _T("\r\n\r\nインストールオプションについて\r\n\r\n ショートカットを上書きしない：アップデイトの際、選択可能となります。ショートカットの作成処理されません。"),
IDS_note15, _T("\r\n\r\n 設定ファイルを上書きしない：アップデイトの際、選択可能となります。インストール先の設定ファイルを置き換えません。"),
IDS_note16, _T("\r\n\r\n GuiEdit 起動高速化：GueEdit.exeのネイティブイメージを作成します。.NET Framework4のインストールがあらかじめ必要となります。"),
IDS_note17, _T("\r\n\r\n デバイスドライバをインストールしない：キーボードLLフックオプションと併用してください。"),
IDS_note18, _T("\r\n\r\n マウスLLフック：マウスフック機能を使うときに設定します。nodoka起動時の引数に-mが設定されます。"),
IDS_note19, _T("\r\n\r\n キーボードLLフック：デバイスドライバを使用しないモードを設定します。nodoka起動時の引数に-kが設定されます。"),
IDS_note20, _T("\r\n\r\n 機能制限版：マクロ機能などが使用できない機能制限版をインストールします。"),
IDS_note21, _T("\r\n\r\n 高整合性レベル(高IL)版：整合性が高い版をインストールします。起動時に管理者権限が必要であり、通常、スタートアップでの自動起動に失敗します。"),
IDS_note22, _T("\r\n\r\n ScancodeMap変更：起動時の引数に-nが設定され、レジストリのScancodeMap変更を実施します。キーボードLLフックオプションと併用可能です。"),
IDS_note23, _T("\r\n\r\n インストール時の詳細については、ヘルプをご覧ください。http://www.appletkan.com/nodoka-doc/README-ja.html"),
IDS_nodokaSetup, _T("Nodoka Setup"),
IDS_nodokaRunning, _T("Nodoka is running. To continue this process, exit the Nodoka?\nPlease wait up to 60 seconds."),
IDS_nodokaEmpty, _T("Select destination directory."),
IDS_selectDir, _T("Select destination directory."),
IDS_invalidDirectory, _T("Invalid directory."),
IDS_removeOk, _T("Are you sure to uninstall Nodoka?"),
IDS_removeFinish, _T("Nodoka is uninstalled."),
IDS_copyFinish, _T("Install complete."),
IDS_error, _T("An error happened !"),
IDS_alreadyUninstalled, _T("Nodoka has been uninstalled.\nPlease reboot Windows, then run this setup program again."),
IDS_notAdministrator, _T("Only Administrator can complete install."),
IDS_invalidOS, _T("Only for Windows 10"),
IDS_nodokaFile, _T("Nodoka file"),
IDS_nodokaShellOpen, _T("notepad.exe \"%1\""),
IDS_nodoka, _T("Nodoka"),
IDS_nodokad, _T("Nodoka driver"),
IDS_shortcutName, _T("Nodoka"),
IDS_shortcutName2, _T("dotnet_starter"),
IDS_keyboard109usb, _T("Japanese 109 (106) Keybaord"),
IDS_keyboard104usb, _T("Standard 104 (101) Keyboard"),
IDS_dotnodoka, _T("doten.nodoka"),
IDS_copyFinishUsb, _T("Install complete.  Do you want to reboot now?"),
IDS_failedToReboot, _T("Failed to reboot."),
IDS_installerror, _T("An error happened !\nPlease reboot Windows, then run this setup program again."),
IDS_detectfilterdriver, _T("Detect keyboard class device device driver. \r\nNodoka does not work, maybe. \r\nDo you need Installation by your responsible ?"),
IDS_selectDirNODOKA, _T("Select EnvironmentVariable NODOKA directory. Use setting file target."),
IDS_shortcutNameGUI, _T("NodokaGuiEdit"),
IDS_note01, _T(" Nodoka is a key remapping tool that uses a keyboard class filter device driver."),
IDS_note02, _T(" Therefore, if a keyboard filter driver other than the standard one is installed, Nodoka may not function correctly, and a warning dialog will be displayed during installation.\r\n"),
IDS_note03, _T(" It is up to the user to decide, but in that case, please uninstall any software that uses that filter driver beforehand.\r\n"),
IDS_note04, _T(" For example, Logitech's SetPoint software, and keyboard filter driver like to use is to change the keyboard layout.\r\n\r\n"),
IDS_note05, _T(" Nodoka during the upgrade installation, the device driver not successfully registered, you may terminate the installation."),
IDS_note06, _T("In this case, Please Reboot and re-install.\r\n\r\n"),
IDS_note07, _T(" License is EPL 2.0 (Eclipse Public License 2.0). Details are included in the zip file as LICENSE.txt, Please, Check it.\r\n\r\n"),
IDS_note08, _T(" Digital sign for device drivers and application programs has become a shareware.\r\n\r\n"),
IDS_note09, _T(" Trial version is the Terminate automatically after 30 minutes. Other differences are not from the retail version.\r\n\r\n"),
IDS_note10, _T(" We are working to resolve problems of software and documentation."),
IDS_note11, _T("However, any errors, defects, failure, if an accident occurs, all case are user's risk."),
IDS_note12, _T("If You do not understand this risk, then, Please do not use this software .\r\n\r\n"),
IDS_note13, _T("  When a new version release, unless a major upgrade, do not have to pay the shareware fee."),
IDS_note14, _T("\r\n\r\nInstall Option.\r\n\r\n Don't revise shortcat : for update install."),
IDS_note15, _T("\r\n\r\n Don't revise dot.nodoka setting files : for update install."),
IDS_note16, _T("\r\n\r\n GuiEdit QuickStart : make native image for GuiEdit.exe. You need Install NET Framework4 runtime."),
IDS_note17, _T("\r\n\r\n Don't Install Device Driver : Use option keyboad LL hook."),
IDS_note18, _T("\r\n\r\n mouse LL hook : Use mouse hook. add nodoka.exe argument \"-m\"."),
IDS_note19, _T("\r\n\r\n keyboard LL hook : Use keyboard hook. Not use device driver. add nodoka.exe argument \"-k\"."),
IDS_note20, _T("\r\n\r\n Limit Version : Use function and macro key limit version."),
IDS_note21, _T("\r\n\r\n High IL Version : Use High Integrity version. You must administrator."),
IDS_note22, _T("\r\n\r\n Reload ScancodeMap : Use option keyboard LL Hook. add nodoka.exe argument \"-n\""),
IDS_note23, _T("\r\n\r\n How to Install, Please see http://www.appletkan.com/en/howtoinsatll_and_capslock_custom.htm"),
