// Copyright 2008-2026 applet <applet@bp.iij4u.or.jp>
// License: EPL-2.0 - https://www.eclipse.org/legal/epl-2.0/

#ifndef _IOCTL_H
#define _IOCTL_H

// Ioctl value
#define IOCTL_NODOKA_DETOUR_CANCEL					 \
	CTL_CODE(FILE_DEVICE_KEYBOARD, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_NODOKA_GET_VERSION					 \
	CTL_CODE(FILE_DEVICE_KEYBOARD, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_NODOKA_GET_LOG					 \
	CTL_CODE(FILE_DEVICE_KEYBOARD, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // !_IOCTL_H
