#!/usr/bin/perl -w

if ( $#ARGV < 3 ) {
  printf("usage: geniexpress SFX.EXE TITLE SETUP.EXE [Files...]\n");
  exit(1);
}

$TargetName   = shift @ARGV;
$FriendlyName = shift @ARGV;
$AppLaunched  = shift @ARGV;

# If TargetName has no directory component, IExpress generates the RPT file
# path incorrectly (leading "\" + "-" + name, resolving to C:\-name.RPT).
# Prepend ".\" so IExpress has an explicit directory and computes the RPT
# path correctly relative to the current directory.
$TargetName = ".\\" . $TargetName unless $TargetName =~ m{[/\\]};

$template = <<"__EOM__";
[Version]
Class=IEXPRESS
SEDVersion=3

[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=$TargetName
FriendlyName=$FriendlyName
AppLaunched=$AppLaunched
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles

[SourceFiles]
SourceFiles0=.\\

[SourceFiles0]
__EOM__

foreach $i ( sort @ARGV ) {
  # NMAKE の行継続で行頭の「=」がマクロ値に入ると単独の「=」引数になり、
  # IExpress の .sed に「==」のような無効行が出る。パス以外は無視する。
  next if ( $i eq '' || $i eq '=' );
  # このリポジトリの distrib は相対パスが ..\ で始まる
  next unless ( $i =~ m{^\.\.[/\\]} );
  $template .= "$i=\n";
}
print $template;
